include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  plugins:
    - custom_lint
  exclude:
    - plugins/**
    - lib/clash/generated/**
    - lib/models/generated/**
    - lib/providers/generated/**
    - lib/l10n/intl/**
