targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/models/{{}}.dart': 'lib/models/generated/{{}}.g.dart'
            '^lib/providers/{{}}.dart': 'lib/providers/generated/{{}}.g.dart'
      freezed:
        options:
        cd /Users/pangxingzhong/Desktop/workspace/zhuquejiasu && find "$HOME/Library/Application Support/com.follow.clash/profiles" -name '*.yaml' -delete && flutter clean && flutter run --release -d macos | tee flutter_app.log  build_extensions:
            '^lib/models/{{}}.dart': 'lib/models/generated/{{}}.freezed.dart'