name: zhuquejiasu
description: zhuque
publish_to: 'none'
version: 0.9.08+2025101715
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.1
  path: ^1.9.0
  shared_preferences: ^2.5.1
  window_manager: ^0.5.1
  dynamic_color: ^1.7.0
  proxy:
    path: plugins/proxy
  window_ext:
    path: plugins/window_ext
  launch_at_startup: ^0.5.1
  windows_single_instance: ^1.0.1
  json_annotation: ^4.9.0
  file_picker: ^10.3.3
  mobile_scanner: ^7.1.2
  app_links: ^6.4.1
  win32_registry: ^2.1.0
  tray_manager: ^0.5.1
  collection: ^1.18.0
  animations: ^2.0.11
  package_info_plus: ^9.0.0
  url_launcher: ^6.2.6
  freezed_annotation: ^3.1.0
  image_picker: ^1.1.2
  webdav_client: ^1.2.2
  dio: ^5.8.0
  crypto: ^3.0.2
  win32: ^5.5.1
  ffi: ^2.1.2
  re_editor: ^0.8.0
  re_highlight: ^0.0.3
  archive: ^4.0.7
  lpinyin: ^2.0.3
  emoji_regex: ^0.0.5
  process_run: ^1.1.0
  cached_network_image: ^3.4.0
  hotkey_manager: ^0.2.3
  uni_platform: ^0.1.3
  device_info_plus: ^12.1.0
  connectivity_plus: ^7.0.0
  screen_retriever: ^0.2.0
  defer_pointer: ^0.0.2
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  riverpod: ^3.0.3
  google_fonts: ^6.2.1

  # 本地持久化
  sp_util: ^2.0.3
  # 通用工具类
  common_utils: ^2.1.0

  get: ^4.7.2

  # 加载提示
  flutter_easyloading: ^3.0.5

  flutter_screenutil: ^5.9.3

  provider: ^6.1.2

  open_file: ^3.5.10

  encrypt: ^5.0.3

  # 新增依赖
  socks5_proxy: ^1.0.4
  proxy_manager: ^0.0.3
  logger: ^2.0.2+1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # ffigen: ^15.0.0  # 已禁用，使用预生成的FFI绑定
  json_serializable: ^6.7.1
  build_runner: ^2.4.13
  args: ^2.4.2
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3



flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/avatars/
    - assets/data/
  fonts:
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
# ffigen配置已禁用，使用预生成的clash_ffi.dart
# ffigen:
#   name: "ClashFFI"
#   output: 'lib/clash/generated/clash_ffi.dart'
#   headers:
#     entry-points:
#       - 'libclash/android/arm64-v8a/libclash.h'
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n
