name: fl_clash
description: zhuque
publish_to: 'none'
version: 0.9.04+202503101
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.1
  path: ^1.9.0
  shared_preferences: ^2.5.1
  window_manager: ^0.4.3
  dynamic_color: ^1.7.0
  proxy:
    path: plugins/proxy
  window_ext:
    path: plugins/window_ext
  launch_at_startup: ^0.2.2
  windows_single_instance: ^1.0.1
  json_annotation: ^4.9.0
  file_picker: ^8.0.3
  mobile_scanner: ^6.0.2
  app_links: ^3.5.0
  win32_registry: ^1.1.5
  tray_manager: ^0.3.2
  collection: ^1.18.0
  animations: ^2.0.11
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  freezed_annotation: ^2.4.1
  image_picker: ^1.1.2
  webdav_client: ^1.2.2
  dio: ^5.8.0
  win32: ^5.5.1
  ffi: ^2.1.2
  re_editor: ^0.6.0
  re_highlight: ^0.0.3
  archive: ^3.6.1
  lpinyin: ^2.0.3
  emoji_regex: ^0.0.5
  process_run: ^1.1.0
  cached_network_image: ^3.4.0
  hotkey_manager: ^0.2.3
  uni_platform: ^0.1.3
  device_info_plus: ^10.1.2
  connectivity_plus: ^6.1.0
  screen_retriever: ^0.2.0
  defer_pointer: ^0.0.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod: ^2.6.1
  google_fonts: ^6.2.1

  # 本地持久化
  sp_util: ^2.0.3
  # 通用工具类
  common_utils: ^2.1.0

  get: ^4.7.2

  # 加载提示
  flutter_easyloading: ^3.0.5

  flutter_screenutil: ^5.9.3

  provider: ^6.1.2

  open_file: ^3.5.10

  encrypt: ^5.0.3

  # 新增依赖
  socks5_proxy: ^1.0.4
  proxy_manager: ^0.0.3
  logger: ^2.0.2+1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  ffigen: ^15.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.13
  args: ^2.4.2
  freezed: ^2.5.1
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3



flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/avatars/
  fonts:
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
ffigen:
  name: "ClashFFI"
  output: 'lib/clash/generated/clash_ffi.dart'
  headers:
    entry-points:
      - 'libclash/android/arm64-v8a/libclash.h'
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n
