display_name: ZhuqueJiasu

packager: pangxingzhong1983
packagerEmail: pangxingzhong1983@gmail.com
license: Other

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

keywords:
  - ZhuqueJiasu
  - Clash
  - ClashMeta
  - Proxy

generic_name: ZhuqueJiasu

group: Applications/Internet

startup_notify: true
