display_name: ZhuqueJiasu

icon: ./assets/images/icon.png

keywords:
  - ZhuqueJiasu
  - Clash
  - ClashMeta
  - Proxy

generic_name: ZhuqueJiasu


categories:
  - Network

startup_notify: true

include: []