display_name: ZhuqueJiasu
package_name: ZhuqueJiasu
maintainer:
  name: pangxingzhong1983
  email: pangxingzhong1983@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png


keywords:
  - ZhuqueJiasu
  - Clash
  - ClashMeta
  - Proxy

generic_name: ZhuqueJiasu

categories:
  - Network

startup_notify: true
