name: CI
on: [push, pull_request]
jobs:
  analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: 'stable' }
      - run: flutter pub get
<<<<<<< HEAD
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings || true
=======
      - run: flutter analyze
>>>>>>> 7c7c81c (ci: add analyze/build checks for branch protection)
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: 'stable' }
      - run: flutter pub get
<<<<<<< HEAD
      - run: flutter build macos --release || true
=======
      - run: flutter build macos --release
>>>>>>> 7c7c81c (ci: add analyze/build checks for branch protection)
