name: release

on:
  workflow_dispatch: {}
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Generate SHA256 checksums
        run: |
          set -euxo pipefail
          cd dist
          find . -type f ! -name 'SHA256SUMS.txt' -print0 | sort -z | xargs -0 sha256sum > SHA256SUMS.txt

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.apk
            dist/**/*.zip
            dist/**/*.exe
            dist/**/*.deb
            dist/**/*.dmg
            dist/SHA256SUMS.txt
